baseURL = 'https://blog.ericyd.com/'
languageCode = 'en-us'
# TODO: need a real title
title = "Musings from my desk"
enableGitInfo = true

# Used in opengraph template
[params]
  description = 'Miscellaneous writings from the premier blogger in the entire world'
  title = 'Musings from my desk'


# Disabling taxonomies for now because I don't want/need the complexity.
# Can deal with this later if desired
# https://gohugo.io/content-management/taxonomies/#configure-taxonomies
[taxonomies]
#  tags = "tags"


[markup]
  [markup.highlight]
    # other options here https://xyproto.github.io/splash/docs/all.html
    # style = 'gruvbox'
    # style = 'catppuccin-macchiato'
    # style = 'solarized-dark'
    style = 'nord'

# Source: https://github.com/regisphilibert/hugoGetApi/
[outputs]
# When this is un-commented, the `/micro` directory will generate 2 outputs: JSON and HTML.
# HTML is the default, so without specifying this config, HTML will always be generated.
# My goal with JSON was to generate a JSON file and make my micro blog data-drive with a little helper JS, à la https://github.com/ericyd/generative-art/blob/b584b6d05e00e533f4c5bdacf23f92aee48f9ac7/docs/index.html#L55-L340
# The problem I'm not sure how to solve yet is how to make the dynamic routes work correctly, for individual microblogs.
# I would like someone to be able to link to a direct microblog, but I'm not sure if it's possible to handle "route params" in Cloudflare pages and/or Hugo.
#  section = ["json", "html"]
  section = ["html"]

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
